name: Build tool on Linux
on:
  push:
  pull_request:
jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
     MAKEFLAGS: -j4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
         sudo apt-get install --yes \
           gcc g++ cmake libgmp-dev libboost-dev libboost-filesystem-dev \
           libboost-thread-dev libboost-test-dev \
           libsqlite3-dev libtbb-dev libz-dev libedit-dev \
           python3 python3-pip \
           llvm-14 llvm-14-dev llvm-14-tools clang-14
      - name: Compile IKOS
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_INSTALL_PREFIX="/opt/ikos" \
            -DCMAKE_BUILD_TYPE="Debug" \
            -DLLVM_CONFIG_EXECUTABLE="/usr/lib/llvm-14/bin/llvm-config" \
            ..
          make
          sudo make install
      - name: Add IKOS to the path
        run: |
          echo "/opt/ikos/bin" >> $GITHUB_PATH
      - name: Confirm that it runs
        run: |
          ikos --version
