name: Build tool on OSX
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    env:
      LDFLAGS:  "-L/opt/homebrew/opt/llvm@14/lib"
      CPPFLAGS: "-I/opt/homebrew/opt/llvm@14/include"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew tap nasa-sw-vnv/core
          brew install cmake gmp boost tbb llvm@14 apron sqlite
      - name: Adjust path
        run:
          echo "/opt/homebrew/opt/llvm@14/bin" >> $GITHUB_PATH
      - name: Test LLVM
        run: |
          which llvm-config
      - name: Compile IKOS
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_INSTALL_PREFIX="$HOME/ikos" \
            -DCMAKE_BUILD_TYPE="Debug" \
            -DLLVM_CONFIG_EXECUTABLE="$(which llvm-config)" \
            -DPYTHON_EXECUTABLE:FILEPATH="$(which python3)" \
            ..
          make
          make install
      - name: Add IKOS to the path
        run: |
          echo "$HOME/ikos/bin" >> $GITHUB_PATH
      - name: Confirm that it runs
        run: |
          ikos --version
